"""
Synthetic check — Tier-1 read-only agent.

Hourly: hits 6 critical endpoints with the public demo key, classifies every
response into pass / 4xx / 5xx / network-error, and raises a GitHub Issue
labelled `incident:errors` whenever the 5xx + network-error rate exceeds the
threshold (default 20% over a single run).

Distinct from `uptime_watcher.py`:
  - Uptime watches /healthz only (every 5 min, low cost).
  - Synthetic exercises real user paths (every hour, slightly heavier).

Required env: same set as uptime_watcher.py.
Public demo key: `al_demo_agentlens` (seeded by api/routes/admin.py on startup).
"""
from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.request

logger = logging.getLogger("synthetic")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

URL = os.environ.get("AGENTLENS_URL", "https://www.agentlens.one").rstrip("/")
DEMO_KEY = os.environ.get("AGENTLENS_DEMO_KEY", "al_demo_agentlens")
THRESHOLD = float(os.environ.get("ERROR_RATE_THRESHOLD", "0.20"))  # 20%
TIMEOUT = float(os.environ.get("SYNTHETIC_TIMEOUT", "10"))
LABEL = "incident:errors"

REPO = os.environ.get("GITHUB_REPOSITORY", "")
GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GH_API = "https://api.github.com"


# Endpoints to probe. (path, method, requires_demo_key, expected_status_set)
PROBES = [
    ("/healthz",                  "GET",  False, {200}),
    ("/",                         "GET",  False, {200}),
    ("/dashboard",                "GET",  False, {200}),
    ("/requests/stats",           "GET",  True,  {200}),
    ("/debug/requests?limit=1",   "GET",  True,  {200}),
    ("/traces?limit=1",           "GET",  True,  {200}),
]


def fetch(path: str, method: str, with_key: bool) -> tuple[int | str, str]:
    """Return (status_or_error, detail). status_or_error is int on HTTP, str on network error."""
    headers = {"User-Agent": "agentlens-synthetic/1.0"}
    if with_key:
        headers["X-API-Key"] = DEMO_KEY
    req = urllib.request.Request(f"{URL}{path}", method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return resp.status, ""
    except urllib.error.HTTPError as e:
        body = e.read(200).decode("utf-8", errors="replace")
        return e.code, body
    except Exception as e:
        return f"ERR:{type(e).__name__}", str(e)[:200]


# ── GitHub Issue glue (same as uptime_watcher) ────────────────────────────────

def gh_request(method: str, path: str, payload: dict | None = None):
    if not (REPO and GH_TOKEN):
        return None
    url = f"{GH_API}/repos/{REPO}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url,
        method=method,
        data=data,
        headers={
            "Authorization": f"Bearer {GH_TOKEN}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "agentlens-synthetic/1.0",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read()
            return json.loads(body) if body else None
    except urllib.error.HTTPError as e:
        logger.warning("GH %s %s → HTTP %s: %s", method, path, e.code, e.read()[:200])
        return None


def find_open_incident():
    issues = gh_request("GET", f"/issues?state=open&labels={LABEL}&per_page=1") or []
    return issues[0] if issues else None


def open_incident(summary: str, table: str):
    body = (
        f"AgentLens synthetic check failed.\n\n"
        f"{summary}\n\n"
        f"```\n{table}\n```\n\n"
        "_Auto-generated by `agents/synthetic_check.py`. Will close on next green run._"
    )
    return gh_request(
        "POST",
        "/issues",
        {"title": f"⚠️ Synthetic errors {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}", "body": body, "labels": [LABEL]},
    )


def close_incident(number: int, table: str):
    gh_request(
        "POST",
        f"/issues/{number}/comments",
        {"body": f"✅ Recovered. Latest run all green:\n\n```\n{table}\n```"},
    )
    gh_request("PATCH", f"/issues/{number}", {"state": "closed"})


# ── Email ─────────────────────────────────────────────────────────────────────

def send_email(subject: str, body: str) -> None:
    api_key = os.environ.get("SENDGRID_API_KEY")
    sender = os.environ.get("SENDER_EMAIL")
    recipient = os.environ.get("OPS_EMAIL")
    if not (api_key and sender and recipient):
        logger.info("Email creds missing — would have sent: %s", subject)
        return
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        msg = Mail(from_email=sender, to_emails=recipient, subject=subject, plain_text_content=body)
        SendGridAPIClient(api_key).send(msg)
    except Exception:
        logger.exception("SendGrid send failed; subject=%s", subject)


# ── Main ──────────────────────────────────────────────────────────────────────

def render_table(results: list[dict]) -> str:
    width_path = max(len(r["path"]) for r in results)
    lines = [f"  {'PATH'.ljust(width_path)}  STATUS"]
    for r in results:
        marker = "✓" if r["pass"] else "✗"
        lines.append(f"{marker} {r['path'].ljust(width_path)}  {r['status']}")
    return "\n".join(lines)


def main() -> int:
    results = []
    for path, method, with_key, expected in PROBES:
        status, detail = fetch(path, method, with_key)
        ok = isinstance(status, int) and status in expected
        results.append({
            "path": path,
            "status": str(status) + (f" — {detail[:80]}" if detail and not ok else ""),
            "pass": ok,
            "is_5xx": isinstance(status, int) and status >= 500,
            "is_network_err": isinstance(status, str),
        })

    table = render_table(results)
    logger.info("Synthetic results:\n%s", table)

    error_count = sum(1 for r in results if r["is_5xx"] or r["is_network_err"])
    error_rate = error_count / len(results) if results else 0
    incident = find_open_incident()

    if error_rate > THRESHOLD:
        summary = f"Error rate **{error_rate:.0%}** ({error_count}/{len(results)}) — threshold {THRESHOLD:.0%}."
        if incident:
            gh_request(
                "POST",
                f"/issues/{incident['number']}/comments",
                {"body": f"Still failing at <code>{time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}</code>.\n\n```\n{table}\n```"},
            )
            logger.info("Issue #%s already open — appended tick", incident["number"])
        else:
            issue = open_incident(summary, table)
            issue_url = (issue or {}).get("html_url", "n/a")
            send_email(
                f"[Synthetic] ⚠️ {error_count}/{len(results)} probes failed",
                f"AgentLens synthetic check above threshold.\n\n{summary}\n\nResults:\n{table}\n\nIncident: {issue_url}\n",
            )
        return 0

    # Healthy — close any open incident
    if incident:
        close_incident(incident["number"], table)
        send_email(
            "[Synthetic] ✅ Recovered",
            f"All synthetic probes passing again.\n\n{table}\n",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
