"""
Uptime watcher — Tier-1 read-only agent.

Pings agentlens.one/healthz on every cron tick. Uses a single GitHub Issue
labeled `incident:uptime` as state, so we only email on incident open/close —
not every 5 minutes during a long outage.

Behaviour:
  - PASS → close any open `incident:uptime` issue with a "resolved" comment;
           if it was open >2 minutes, send a recovery email.
  - FAIL → if no open issue, create one + email Soufian.
           if there's already one, append a tick comment (no email).

Required env (GitHub Actions provides the first three):
  GITHUB_REPOSITORY    e.g. Soufianeazz/agentlens
  GITHUB_TOKEN         provided by GH Actions (needs issues: write)
  AGENTLENS_URL        https://www.agentlens.one
  SENDGRID_API_KEY     optional — without it the email step is logged-only
  SENDER_EMAIL         optional
  OPS_EMAIL            optional

Exits 0 unless something genuinely broken happens (so cron itself stays green).
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
import urllib.error
import urllib.request

logger = logging.getLogger("uptime")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

URL = os.environ.get("AGENTLENS_URL", "https://www.agentlens.one").rstrip("/")
HEALTHZ = f"{URL}/healthz"
TIMEOUT = float(os.environ.get("UPTIME_TIMEOUT", "8"))
LABEL = "incident:uptime"

# GitHub API
REPO = os.environ.get("GITHUB_REPOSITORY", "")
GH_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GH_API = "https://api.github.com"


# ── Health check ──────────────────────────────────────────────────────────────

def probe() -> tuple[bool, str]:
    """Return (ok, detail)."""
    try:
        req = urllib.request.Request(HEALTHZ, headers={"User-Agent": "agentlens-uptime/1.0"})
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            status = resp.status
            body = resp.read(2000).decode("utf-8", errors="replace")
            if status == 200 and '"status"' in body and "ok" in body:
                return True, f"200 in healthy body"
            return False, f"HTTP {status} body={body[:200]}"
    except urllib.error.HTTPError as e:
        return False, f"HTTP {e.code} {e.reason}"
    except urllib.error.URLError as e:
        return False, f"URLError: {e.reason}"
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


# ── GitHub issue state ────────────────────────────────────────────────────────

def gh_request(method: str, path: str, payload: dict | None = None) -> dict | list | None:
    if not (REPO and GH_TOKEN):
        logger.warning("GitHub auth missing — running without issue state")
        return None
    url = f"{GH_API}/repos/{REPO}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url,
        method=method,
        data=data,
        headers={
            "Authorization": f"Bearer {GH_TOKEN}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "agentlens-uptime/1.0",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read()
            return json.loads(body) if body else None
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")[:300]
        logger.warning("GH %s %s → HTTP %s: %s", method, path, e.code, body)
        return None


def find_open_incident() -> dict | None:
    issues = gh_request("GET", f"/issues?state=open&labels={LABEL}&per_page=1") or []
    return issues[0] if issues else None


def open_incident(detail: str) -> dict | None:
    body = (
        "AgentLens production health-check failed.\n\n"
        f"- URL: `{HEALTHZ}`\n"
        f"- First failure: <code>{time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}</code>\n"
        f"- Detail: `{detail}`\n\n"
        "_Auto-generated by `agents/uptime_watcher.py`. Will close itself on recovery._"
    )
    return gh_request(
        "POST",
        "/issues",
        {"title": f"⚠️ Uptime incident {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}", "body": body, "labels": [LABEL]},
    )


def append_incident_comment(number: int, detail: str) -> None:
    gh_request(
        "POST",
        f"/issues/{number}/comments",
        {"body": f"Still failing at <code>{time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}</code>: `{detail}`"},
    )


def close_incident(number: int, opened_at_epoch: float) -> float:
    duration_s = max(0, time.time() - opened_at_epoch)
    duration_min = round(duration_s / 60, 1)
    gh_request(
        "POST",
        f"/issues/{number}/comments",
        {"body": (
            f"✅ Recovered at <code>{time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}</code>"
            f" — total downtime ~{duration_min} min."
        )},
    )
    gh_request("PATCH", f"/issues/{number}", {"state": "closed"})
    return duration_min


# ── Email (re-uses pilot_pulse pattern) ───────────────────────────────────────

def send_email(subject: str, body: str) -> None:
    api_key = os.environ.get("SENDGRID_API_KEY")
    sender = os.environ.get("SENDER_EMAIL")
    recipient = os.environ.get("OPS_EMAIL")
    if not (api_key and sender and recipient):
        logger.info("Email creds missing — would have sent: %s", subject)
        return
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        msg = Mail(from_email=sender, to_emails=recipient, subject=subject, plain_text_content=body)
        SendGridAPIClient(api_key).send(msg)
        logger.info("Sent email: %s", subject)
    except Exception:
        logger.exception("SendGrid send failed; subject=%s", subject)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ok, detail = probe()
    logger.info("Probe %s — %s", "OK" if ok else "FAIL", detail)

    incident = find_open_incident()

    if ok:
        if incident:
            opened_at = time.mktime(time.strptime(incident["created_at"], "%Y-%m-%dT%H:%M:%SZ"))
            duration_min = close_incident(incident["number"], opened_at)
            if duration_min >= 2:
                send_email(
                    f"[Uptime] ✅ Recovered after {duration_min} min",
                    f"AgentLens healthz is green again.\n\n"
                    f"Incident #{incident['number']} closed.\n"
                    f"Total downtime: ~{duration_min} min.\n"
                    f"URL: {HEALTHZ}\n",
                )
        return 0

    # Failing
    if incident:
        append_incident_comment(incident["number"], detail)
        logger.info("Incident #%s already open — appended tick", incident["number"])
        return 0

    # New incident
    issue = open_incident(detail)
    issue_url = (issue or {}).get("html_url", "n/a")
    send_email(
        "[Uptime] ⚠️ AgentLens healthz failing",
        f"Health check failed for {HEALTHZ}.\n\n"
        f"Detail: {detail}\n"
        f"Incident: {issue_url}\n\n"
        "Will auto-resolve when /healthz is healthy again.",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
