"""
Read endpoints consumed by the dashboard.
"""
import asyncio
import time
import uuid

from fastapi import APIRouter, Depends, Query
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from api.auth import ApiKeyContext, ensure_role, require_api_key, require_api_key_context
from api.costing import compute_cost_from_tokens, compute_request_cost
from api.plan_access import require_feature, resolve_plan_context
from storage.database import get_session
from storage.models import Evaluation, Request, Span, Trace

router = APIRouter()
_STATS_CACHE_TTL_SECONDS = 5.0
_stats_cache: dict[str, tuple[float, dict]] = {}
_stats_cache_lock = asyncio.Lock()


@router.get("/dashboard/context")
async def dashboard_context(
    db: AsyncSession = Depends(get_session),
    ctx: ApiKeyContext = Depends(require_api_key_context),
):
    plan_ctx = await resolve_plan_context(db=db, ctx=ctx)
    return {
        "raw_plan": plan_ctx.raw_plan,
        "plan": plan_ctx.plan,
        "is_enterprise": plan_ctx.plan == "enterprise",
        "features": plan_ctx.features,
    }


@router.post("/demo/live-run")
async def run_live_demo(
    db: AsyncSession = Depends(get_session),
    ctx: ApiKeyContext = Depends(require_api_key_context),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    """One-click live demo data generation (no terminal required)."""
    ensure_role(ctx, "admin", "analyst")
    now = time.time()

    scenarios = [
        ("marketing_agent", "Launch campaign brief", "gpt-4o-mini", 0.86, 0.08, []),
        ("research_agent", "Competitor pricing benchmark", "gpt-4o", 0.81, 0.12, ["low_detail"]),
        ("support_agent", "Refund complaint response", "gpt-4o-mini", 0.91, 0.04, []),
        ("sales_agent", "Lead qualification outreach", "gpt-4o-mini", 0.84, 0.06, []),
        ("compliance_agent", "GDPR export handling", "gpt-4o", 0.78, 0.18, ["possible_hallucination"]),
    ]

    request_count = 0
    trace_count = 0
    span_count = 0

    for i, (agent_name, task, model, quality, hallucination, flags) in enumerate(scenarios, start=1):
        ts = now - (i * 90)
        # Two prompt-debug entries per scenario for immediate dashboard impact.
        for j in range(2):
            req_id = str(uuid.uuid4())
            prompt = f"Agent={agent_name} | task={task} | step={j+1}"
            input_text = f"{task} - user request #{j+1}"
            output_text = (
                f"{task} completed with clear next steps and ownership."
                if j == 0
                else f"{task} follow-up note with concise summary and risk callouts."
            )
            input_tokens = max(10, len(input_text) // 4) + (20 * (j + 1))
            output_tokens = max(10, len(output_text) // 4) + (18 * (j + 1))
            cost = compute_cost_from_tokens(model, input_tokens, output_tokens) or 0.0

            db.add(
                Request(
                    id=req_id,
                    api_key=ctx.key,
                    input=input_text,
                    output=output_text,
                    prompt=prompt,
                    model=model,
                    metadata_={
                        "feature": agent_name.replace("_agent", ""),
                        "input_tokens": input_tokens,
                        "output_tokens": output_tokens,
                        "cost_usd": cost,
                        "source": "live_demo_button",
                    },
                    timestamp=ts - (j * 15),
                )
            )
            db.add(
                Evaluation(
                    request_id=req_id,
                    quality_score=round(max(0.01, quality - (0.04 * j)), 3),
                    hallucination_score=round(min(0.99, hallucination + (0.03 * j)), 3),
                    flags=flags if j == 0 else (flags or ["too_short"]),
                    score_explanation="Generated by one-click live demo scenario.",
                )
            )
            request_count += 1

        # Agent debugger trace with 3 spans.
        trace_id = str(uuid.uuid4())
        trace_status = "failed" if "possible_hallucination" in flags else "completed"
        trace_output = None if trace_status == "failed" else f"{task} finished successfully."
        trace_error = "Evidence mismatch detected in compliance check." if trace_status == "failed" else None
        trace_start = ts - 40
        span_templates = [
            ("retrieve_context", "retrieval", 150, None),
            ("reason_and_draft", "llm", 420, model),
            ("finalize_response", "decision", 120, None),
        ]
        trace_total_tokens = 0.0
        trace_total_cost = 0.0
        for idx, (span_name, span_type, duration_ms, span_model) in enumerate(span_templates, start=1):
            s_id = str(uuid.uuid4())
            s_input = f"{span_name} for {task}"
            s_output = f"{span_name} output ready"
            tokens = 0.0
            cost = 0.0
            if span_model:
                tokens = 280 + (idx * 60)
                est_in = int(tokens * 0.6)
                est_out = int(tokens - est_in)
                cost = compute_cost_from_tokens(span_model, est_in, est_out) or 0.0
            status = "failed" if (trace_status == "failed" and idx == 2) else "completed"
            error = "LLM confidence below threshold." if status == "failed" else None
            db.add(
                Span(
                    id=s_id,
                    trace_id=trace_id,
                    parent_span_id=None,
                    name=span_name,
                    span_type=span_type,
                    status=status,
                    input=s_input,
                    output=s_output if status == "completed" else None,
                    model=span_model,
                    tokens=tokens if tokens > 0 else None,
                    cost_usd=round(cost, 8) if cost > 0 else None,
                    duration_ms=duration_ms,
                    error=error,
                    metadata_={"source": "live_demo_button"},
                    started_at=trace_start + ((idx - 1) * 0.25),
                    ended_at=trace_start + ((idx - 1) * 0.25) + (duration_ms / 1000.0),
                )
            )
            trace_total_tokens += tokens
            trace_total_cost += cost
            span_count += 1

        db.add(
            Trace(
                id=trace_id,
                api_key=ctx.key,
                name=agent_name,
                status=trace_status,
                input=task,
                output=trace_output,
                total_tokens=trace_total_tokens,
                total_cost_usd=round(trace_total_cost, 8),
                total_duration_ms=690.0,
                error=trace_error,
                metadata_={"source": "live_demo_button"},
                started_at=trace_start,
                ended_at=trace_start + 0.69,
            )
        )
        trace_count += 1

    await db.commit()
    _stats_cache.pop(ctx.key, None)
    return {
        "ok": True,
        "requests_created": request_count,
        "traces_created": trace_count,
        "spans_created": span_count,
    }


@router.get("/requests/worst")
async def worst_responses(
    limit: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    result = await db.execute(
        select(Request, Evaluation)
        .join(Evaluation, Evaluation.request_id == Request.id)
        .where(Request.api_key == api_key)
        .order_by(Evaluation.quality_score.asc())
        .limit(limit)
    )
    rows = result.all()
    return [
        {
            "request_id": req.id,
            "model": req.model,
            "timestamp": req.timestamp,
            "quality_score": ev.quality_score,
            "hallucination_score": ev.hallucination_score,
            "flags": ev.flags,
            "score_explanation": ev.score_explanation,
            "input_preview": req.input[:120],
            "output_preview": req.output[:120],
        }
        for req, ev in rows
    ]


@router.get("/requests/trend")
async def quality_trend(
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
):
    sql = text(
        """
        SELECT
            strftime('%Y-%m-%dT%H:00:00', datetime(r.timestamp, 'unixepoch')) AS hour,
            AVG(e.quality_score) AS avg_quality
        FROM requests r
        JOIN evaluations e ON e.request_id = r.id
        WHERE r.timestamp >= strftime('%s','now','-1 day')
          AND r.api_key = :api_key
        GROUP BY hour
        ORDER BY hour ASC
        """
    )
    result = await db.execute(sql, {"api_key": api_key})
    return [{"hour": row.hour, "avg_quality": row.avg_quality} for row in result]


@router.get("/requests/clusters")
async def bad_response_clusters(
    quality_threshold: float = Query(0.7, ge=0.0, le=1.0),
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    result = await db.execute(
        select(Evaluation)
        .join(Request, Request.id == Evaluation.request_id)
        .where(Request.api_key == api_key, Evaluation.quality_score < quality_threshold)
    )
    evaluations = result.scalars().all()

    clusters: dict[str, dict] = {}
    for ev in evaluations:
        flags = ev.flags or ["unflagged"]
        primary = flags[0] if flags else "unflagged"
        if primary not in clusters:
            clusters[primary] = {"category": primary, "count": 0, "total_quality": 0.0, "total_hallucination": 0.0}
        clusters[primary]["count"] += 1
        clusters[primary]["total_quality"] += ev.quality_score
        clusters[primary]["total_hallucination"] += ev.hallucination_score

    result_list = []
    for c in sorted(clusters.values(), key=lambda x: -x["count"]):
        n = c["count"]
        result_list.append({
            "category": c["category"],
            "count": n,
            "avg_quality": round(c["total_quality"] / n, 3),
            "avg_hallucination": round(c["total_hallucination"] / n, 3),
        })
    return result_list


@router.get("/requests/root-cause")
async def root_cause_analysis(
    quality_threshold: float = Query(0.6, ge=0.0, le=1.0),
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    result = await db.execute(
        select(Request, Evaluation)
        .join(Evaluation, Evaluation.request_id == Request.id)
        .where(Request.api_key == api_key)
    )
    rows = result.all()

    prompt_stats: dict[str, dict] = {}
    for req, ev in rows:
        key = req.prompt[:80].strip()
        if key not in prompt_stats:
            prompt_stats[key] = {"prompt": req.prompt[:120], "total": 0, "failures": 0,
                                  "total_quality": 0.0, "total_cost": 0.0, "models": set()}
        prompt_stats[key]["total"] += 1
        prompt_stats[key]["total_quality"] += ev.quality_score
        prompt_stats[key]["models"].add(req.model)
        cost = compute_request_cost(req.model, req.metadata_ or {}, req.input, req.output)
        prompt_stats[key]["total_cost"] += cost
        if ev.quality_score < quality_threshold:
            prompt_stats[key]["failures"] += 1

    result_list = []
    for s in prompt_stats.values():
        n = s["total"]
        failure_rate = s["failures"] / n if n > 0 else 0
        result_list.append({
            "prompt_preview": s["prompt"],
            "total_calls": n,
            "failure_rate": round(failure_rate, 3),
            "avg_quality": round(s["total_quality"] / n, 3),
            "total_cost_usd": round(s["total_cost"], 4),
            "models": list(s["models"]),
        })

    return sorted(result_list, key=lambda x: -x["failure_rate"])[:10]


@router.get("/requests/cost-quality")
async def cost_quality_correlation(
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    result = await db.execute(
        select(Request, Evaluation)
        .join(Evaluation, Evaluation.request_id == Request.id)
        .where(Request.api_key == api_key)
    )
    rows = result.all()

    models: dict[str, dict] = {}
    for req, ev in rows:
        m = req.model
        if m not in models:
            models[m] = {"total": 0, "total_quality": 0.0, "total_cost": 0.0, "failures": 0}
        cost = compute_request_cost(req.model, req.metadata_ or {}, req.input, req.output)
        models[m]["total"] += 1
        models[m]["total_quality"] += ev.quality_score
        models[m]["total_cost"] += cost
        if ev.quality_score < 0.6:
            models[m]["failures"] += 1

    result_list = []
    for model, s in models.items():
        n = s["total"]
        result_list.append({
            "model": model,
            "avg_quality": round(s["total_quality"] / n, 3),
            "avg_cost_usd": round(s["total_cost"] / n, 6),
            "total_calls": n,
            "failure_rate": round(s["failures"] / n, 3),
        })

    return sorted(result_list, key=lambda x: -x["avg_quality"])


@router.get("/requests/stats")
async def overview_stats(
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
):
    now = time.monotonic()
    cached = _stats_cache.get(api_key)
    if cached and now - cached[0] <= _STATS_CACHE_TTL_SECONDS:
        return cached[1]

    # Guard against thundering herd under burst traffic for the same API key.
    async with _stats_cache_lock:
        now = time.monotonic()
        cached = _stats_cache.get(api_key)
        if cached and now - cached[0] <= _STATS_CACHE_TTL_SECONDS:
            return cached[1]

        cutoff = time.time() - 86400
        result = await db.execute(
            select(Request, Evaluation)
            .join(Evaluation, Evaluation.request_id == Request.id)
            .where(Request.api_key == api_key, Request.timestamp >= cutoff)
        )
        rows = result.all()
        total = len(rows)
        total_quality = 0.0
        total_cost = 0.0
        bad_calls = 0
        for req, ev in rows:
            total_quality += ev.quality_score or 0.0
            total_cost += compute_request_cost(req.model, req.metadata_ or {}, req.input, req.output)
            if (ev.quality_score or 0.0) < 0.6:
                bad_calls += 1
        payload = {
            "total_calls_24h": total,
            "avg_quality_24h": round((total_quality / total) if total > 0 else 0, 3),
            "total_cost_24h_usd": round(total_cost, 4),
            "bad_response_rate": round((bad_calls or 0) / total, 3) if total > 0 else 0,
        }
        _stats_cache[api_key] = (time.monotonic(), payload)
        return payload


@router.get("/requests/regression")
async def regression_detection(
    window_minutes: int = Query(60, ge=5, le=1440),
    threshold: float = Query(0.1, ge=0.01, le=1.0),
    db: AsyncSession = Depends(get_session),
    api_key: str = Depends(require_api_key),
    _feature: object = Depends(require_feature("advanced_analytics")),
):
    sql = text(
        """
        SELECT
            AVG(CASE WHEN r.timestamp >= strftime('%s','now',:neg_window) THEN e.quality_score END) AS current_avg,
            AVG(CASE WHEN r.timestamp >= strftime('%s','now',:neg_double)
                      AND r.timestamp <  strftime('%s','now',:neg_window) THEN e.quality_score END) AS previous_avg,
            COUNT(CASE WHEN r.timestamp >= strftime('%s','now',:neg_window) THEN 1 END) AS current_count,
            COUNT(CASE WHEN r.timestamp >= strftime('%s','now',:neg_double)
                        AND r.timestamp < strftime('%s','now',:neg_window) THEN 1 END) AS previous_count
        FROM requests r
        JOIN evaluations e ON e.request_id = r.id
        WHERE r.timestamp >= strftime('%s','now',:neg_double)
          AND r.api_key = :api_key
        """
    )
    neg_window = f"-{window_minutes} minutes"
    neg_double = f"-{window_minutes * 2} minutes"
    row = (await db.execute(sql, {"neg_window": neg_window, "neg_double": neg_double, "api_key": api_key})).one()

    current_avg = row.current_avg
    previous_avg = row.previous_avg

    if current_avg is None or previous_avg is None:
        return {
            "regression_detected": False,
            "reason": "not enough data in one or both windows",
            "current_avg": current_avg,
            "previous_avg": previous_avg,
            "current_count": row.current_count,
            "previous_count": row.previous_count,
            "window_minutes": window_minutes,
        }

    drop = previous_avg - current_avg
    regression = drop >= threshold

    return {
        "regression_detected": regression,
        "reason": f"quality dropped by {drop:.3f} (threshold {threshold})" if regression else "quality stable",
        "current_avg": round(current_avg, 3),
        "previous_avg": round(previous_avg, 3),
        "drop": round(drop, 3),
        "current_count": row.current_count,
        "previous_count": row.previous_count,
        "window_minutes": window_minutes,
    }
